version: '3.8'

services:
  # Frontend Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://backend:3001
      - REACT_APP_ENVIRONMENT=production
    depends_on:
      - backend
    networks:
      - finance-network
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: unless-stopped

  # Backend API Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - MONGODB_URI=mongodb://mongodb:27017/finance_dashboard
      - JWT_SECRET=your_jwt_secret_here
      - CORS_ORIGIN=http://frontend:3000
    depends_on:
      - mongodb
    networks:
      - finance-network
    volumes:
      - ./backend:/app
      - /app/node_modules
    restart: unless-stopped

  # MongoDB Database Service
  mongodb:
    image: mongo:7.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password123
      - MONGO_INITDB_DATABASE=finance_dashboard
    volumes:
      - mongodb_data:/data/db
      - ./mongodb/init:/docker-entrypoint-initdb.d
    networks:
      - finance-network
    restart: unless-stopped

  # Nginx Reverse Proxy (Optional)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - backend
    networks:
      - finance-network
    restart: unless-stopped

networks:
  finance-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
